(()=>{const D=GAME_DATA,KEY="yunchuan-v05-save";let state={mode:"",char:null,scene:null,score:{love:0,trust:0,spark:0},memory:[],turn:1};const el=id=>document.getElementById(id);
function hideAll(){["modes","characters","game","ending","hud"].forEach(x=>el(x).classList.add("hidden"))}
function draw(){el("love").textContent=state.score.love;el("trust").textContent=state.score.trust;el("spark").textContent=state.score.spark;let total=state.score.love+state.score.trust+state.score.spark,rel=total>=34?"曖昧升溫":total>=20?"逐漸熟悉":total>=10?"開始認識":"陌生";el("relation").textContent=rel;el("progressBar").style.width=Math.min(100,state.turn/4*100)+"%"}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function modeHome(){hideAll();el("modes").classList.remove("hidden");el("continueBtn").disabled=!localStorage.getItem(KEY)}
function pickMode(m){state={mode:m,char:null,scene:null,score:{love:0,trust:0,spark:0},memory:[],turn:1};hideAll();el("characters").classList.remove("hidden");el("characterList").innerHTML="";D.characters[m].forEach(c=>{let b=document.createElement("button");b.innerHTML=`${c.avatar}<b>${c.name}</b><span>${c.desc}</span>`;b.onclick=()=>{state.char=c;state.scene=c.start;play(c.start)};el("characterList").appendChild(b)})}
function play(id,analysis=""){if(id==="END"){finish();return}let x=D.scenes[id];state.scene=id;state.turn=x.chapter||state.turn;hideAll();el("hud").classList.remove("hidden");el("game").classList.remove("hidden");el("chapter").textContent=`第 ${state.turn} 章 / 4`;el("stage").textContent=x.stage;el("turn").textContent=`故事進度 ${state.turn}/4`;el("name").textContent=x.name;el("avatar").textContent=x.avatar;el("mood").textContent=x.mood;el("dialog").textContent=x.text;el("analysis").classList.toggle("hidden",!analysis);el("analysisText").textContent=analysis;el("memoryBox").classList.toggle("hidden",!state.memory.length);el("memoryBox").textContent=state.memory.length?"🧠 角色記憶："+state.memory.join("；"):"";el("choices").innerHTML="";x.choices.forEach(c=>{let b=document.createElement("button");b.textContent=c.text;b.onclick=()=>{state.score.love=Math.max(0,state.score.love+c.fx[0]);state.score.trust=Math.max(0,state.score.trust+c.fx[1]);state.score.spark=Math.max(0,state.score.spark+c.fx[2]);if(c.memory&&!state.memory.includes(c.memory))state.memory.push(c.memory);draw();if(c.next==="END")finish(c.analysis);else play(c.next,c.analysis);save()};el("choices").appendChild(b)});draw();save()}
function finish(last=""){hideAll();el("hud").classList.remove("hidden");el("ending").classList.remove("hidden");state.turn=4;draw();let s=state.score,t=s.love+s.trust+s.spark;if(s.trust<5){el("endingIcon").textContent="🌙";el("endingTitle").textContent="保持距離";el("endingText").textContent="這段互動沒有明顯惡化，但信任還需要時間累積。"}else if(t>=35){el("endingIcon").textContent="💞";el("endingTitle").textContent="關係升溫";el("endingText").textContent="你們建立了不錯的互動基礎，故事留下繼續發展的空間。"}else{el("endingIcon").textContent="✨";el("endingTitle").textContent="舒服的開始";el("endingText").textContent="彼此有了一些了解。沒有急著定義關係，也是一種健康的進展。"}el("endingStats").innerHTML=`❤️ 好感 ${s.love}　🤝 信任 ${s.trust}　💘 心動 ${s.spark}${last?`<br><small>${last}</small>`:""}`;save()}
function resume(){try{let x=JSON.parse(localStorage.getItem(KEY));if(!x)return;state=x;if(state.scene)play(state.scene)}catch(e){modeHome()}}
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>pickMode(b.dataset.mode));el("homeBtn").onclick=modeHome;el("modeBtn").onclick=modeHome;el("continueBtn").onclick=resume;el("resetBtn").onclick=()=>{localStorage.removeItem(KEY);modeHome();alert("0.5 遊戲進度已清除")};el("restartBtn").onclick=()=>{let c=state.char;state.score={love:0,trust:0,spark:0};state.memory=[];state.turn=1;play(c.start)};modeHome()})();