window.GAME_DATA={
  version:"0.6",
  characters:{
    boy:[
      {
        id:"yan",
        name:"妍妍",
        avatar:"💄",
        personality:"愛互虧、外向、慢慢觀察",
        location:"便利商店"
      },
      {
        id:"xiaoyu",
        name:"小雨",
        avatar:"🌸",
        personality:"慢熟、溫柔、比較謹慎",
        location:"咖啡店"
      },
      {
        id:"nana",
        name:"娜娜",
        avatar:"✨",
        personality:"直球、活潑、有自己的節奏",
        location:"朋友聚會"
      }
    ],
    girl:[
      {
        id:"kai",
        name:"阿凱",
        avatar:"😎",
        personality:"愛開玩笑、直接",
        location:"LINE聊天"
      },
      {
        id:"hao",
        name:"阿豪",
        avatar:"🧢",
        personality:"嘴硬、慢熱、重視回應",
        location:"朋友聚會"
      },
      {
        id:"yu",
        name:"宇辰",
        avatar:"☕",
        personality:"溫和、觀察型",
        location:"咖啡店"
      }
    ],
    free:[
      {
        id:"momo",
        name:"Momo",
        avatar:"🎭",
        personality:"幽默、自然、重視界線",
        location:"咖啡店"
      },
      {
        id:"sky",
        name:"Sky",
        avatar:"🌙",
        personality:"慢熟、神秘、喜歡聊天",
        location:"書店"
      }
    ]
  },

  scenarios:[
    {
      id:"meet_01",
      title:"第一次注意到你",
      stage:"初識",
      text:"對方看了你一下，笑著說：「欸，我是不是在哪裡看過你？」",
      choices:[
        {
          text:"「可能夢裡吧 😏」",
          effects:{affection:2,trust:0,spark:3},
          reply:"對方笑了一下：「你都這樣跟人聊天喔？」",
          analysis:"帶有玩笑感，可能製造心動，但要觀察對方是否喜歡這種互動。"
        },
        {
          text:"「有可能耶，你常來這附近嗎？」",
          effects:{affection:2,trust:3,spark:1},
          reply:"對方點點頭：「偶爾啊，你呢？」",
          analysis:"自然延續話題，給對方充分回應空間。"
        },
        {
          text:"「應該沒有吧。」",
          effects:{affection:0,trust:1,spark:0},
          reply:"對方笑笑：「好吧，可能我認錯人了。」",
          analysis:"安全但較難延續，可以再補一個開放式問題。"
        }
      ]
    },

    {
      id:"chat_01",
      title:"聊天開始升溫",
      stage:"熟悉",
      text:"晚上對方突然傳訊息：「欸，你睡了沒？」",
      choices:[
        {
          text:"「還沒，怎樣？想我喔？」",
          effects:{affection:2,trust:1,spark:3},
          reply:"對方：「少臭美 😂 只是突然想到你。」",
          analysis:"適合已經有互虧感的關係；若對方反應冷淡就不要硬推。"
        },
        {
          text:"「還沒啊，怎麼了？」",
          effects:{affection:2,trust:3,spark:1},
          reply:"對方：「沒什麼，就想找個人聊一下。」",
          analysis:"自然且給對方表達需求的空間。"
        },
        {
          text:"「要睡了。」",
          effects:{affection:0,trust:1,spark:0},
          reply:"對方：「好，那你早點休息。」",
          analysis:"界線清楚沒有問題，但這次互動可能就此結束。"
        }
      ]
    },

    {
      id:"date_01",
      title:"要不要約出去？",
      stage:"曖昧",
      text:"對方說：「最近好像有一家新開的店很紅。」",
      choices:[
        {
          text:"「那我們找一天一起去？」",
          effects:{affection:3,trust:3,spark:2},
          reply:"對方：「可以啊，你哪天有空？」",
          analysis:"清楚提出邀約，同時保留對方選擇時間的空間。"
        },
        {
          text:"「妳是不是在暗示我約妳？😏」",
          effects:{affection:1,trust:0,spark:3},
          reply:"對方：「你想太多啦 😂」",
          analysis:"可能形成曖昧效果，也可能讓對方有壓力，需要看既有互動程度。"
        },
        {
          text:"「喔，我也有看到。」",
          effects:{affection:0,trust:1,spark:0},
          reply:"對方：「對啊，看起來還不錯。」",
          analysis:"沒有風險，但容易錯過延伸互動的機會。"
        }
      ]
    },

    {
      id:"boundary_01",
      title:"讀懂界線",
      stage:"關係判斷",
      text:"你提出邀約後，對方回答：「最近真的有點忙，先不要約好了。」",
      choices:[
        {
          text:"「好啊，沒問題。有空再聊。」",
          effects:{affection:1,trust:4,spark:0},
          reply:"對方：「好～謝謝你理解。」",
          analysis:"尊重明確表達的界線，通常有助於維持信任。"
        },
        {
          text:"「真的完全沒時間嗎？」",
          effects:{affection:-1,trust:-2,spark:0},
          reply:"對方：「嗯，我現在真的不方便。」",
          analysis:"再次追問可能形成壓力。對方已清楚拒絕時應停止推進。"
        },
        {
          text:"「好，我知道了。」",
          effects:{affection:0,trust:2,spark:0},
          reply:"對方：「嗯嗯。」",
          analysis:"接受對方決定，也是合理且尊重的處理方式。"
        }
      ]
    },

    {
      id:"warm_01",
      title:"關係升溫",
      stage:"升溫",
      text:"聊了一陣子後，對方說：「其實跟你聊天滿舒服的。」",
      choices:[
        {
          text:"「我也是，跟你聊天不用想太多。」",
          effects:{affection:3,trust:4,spark:2},
          reply:"對方：「對啊，這種感覺滿難得的。」",
          analysis:"回應對方感受，同時沒有要求對方立即定義關係。"
        },
        {
          text:"「所以妳喜歡我囉？」",
          effects:{affection:1,trust:-1,spark:3},
          reply:"對方：「欸，我又沒這樣說 😂」",
          analysis:"直接把舒服等同於喜歡可能過度解讀訊號。"
        },
        {
          text:"「哈哈，是喔。」",
          effects:{affection:0,trust:1,spark:0},
          reply:"對方：「嗯啊。」",
          analysis:"安全，但沒有承接對方釋出的情緒訊號。"
        }
      ]
    }
  ]
};
